--- 
kind: pipeline
name: dvstLab
steps: 
  - name: compile-test-latest
    image: "rzlamrr/dvstlab:latest"
    commands:
      - "rm -rf *"
      #- "apt update -qq -y && DEBIAN_FRONTEND=noninteractive apt install -qq -y openjdk-8-jdk cpio"
      - "git clone https://github.com/dvstLab/4.14 -b android-4.14-stable --depth=1 silont"
      - "cd silont"
      - "wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh"
      - "chmod +x compile.sh"
      - "sed -i 's/Image.gz-dtb\ dtbo.img/Image.gz-dtb\ #dtbo.img/g' compile.sh"
      - "bash compile.sh -clang proton -d ranchu64_defconfig -cn Test"
      - "cd .. && rm -rf *"
    environment: 
      TOKED:
        from_secret: TOKED
      CHATID:
        from_secret: CHATID
      ORIGIN:
        from_secret: ORIGIN
      PATF:
        from_secret: PATF
      PAT:
        from_secret: PAT
