kind: pipeline
name: n11

steps:
- name: compile-test
  image: rzlamrr/dvst-builder:latest
  user: root
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - git clone -qq --depth=1 https://github.com/ghostrider-reborn/android_kernel_xiaomi_ginkgo silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c proton -k qs -ci drone -d vendor/ginkgo-perf_defconfig -cn Bluto
  - cd .. && rm -rf *
