kind: pipeline
name: m11

steps:
- name: compile-test
  image: rzlamrr/dvstlab:focal
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
    PATF:
      from_secret: PATF
  commands:
  - git clone --depth=1 https://github.com/fakhiralkda/silonte -b fix silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c proton -ci drone -d silont-perf_defconfig -cn Pertamax
  - cd .. && rm -rf *
