kind: pipeline
name: silont

steps:
- name: compile
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless
  - git clone -qq --depth=1 https://github.com/rzlamrr/silont-ginkgo silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c silont -ci drone
