kind: pipeline
name: silont

steps:
- name: compile
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless
  - git clone -qq $ORIGIN silont -b qsilver
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/fetch-latest-wireguard.sh
  - chmod +x fetch-latest-wireguard.sh compile.sh
  - bash fetch-latest-wireguard.sh
  - ls -a
  - ls out/
  - ls out/arch/arm64/boot
