kind: pipeline
name: n11

steps:
- name: compile-test
  image: rzlamrr/kernel_compile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update -qq -y &&  apt upgrade -qq -y && apt install -qq -y openjdk-11-jre-headless cpio
  - cpio --help
  - git clone -qq --depth=1 $ORIGIN -b n11 silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c silont -ci drone -d vendor/ginkgo-perf_defconfig -cn Test
  - ls -a
  - ls out/
  - ls out/arch/arm64/boot
