kind: pipeline
name: n11

steps:
- name: compile-test
  image: rzlamrr/dvst-builder:latest
  user: root
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
    PATF:
      from_secret: PATF
  commands:
  - git clone --depth=1 https://github.com/fakhiralkda/ginkgo-kernel silont
  - cd silont
  - sed -i 's/CONFIG_LLVM_POLLY/#CONFIG_LLVM_POLLY/g' arch/arm64/configs/vendor/ginkgo-perf_defconfig
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c proton -k qs -ci drone -d vendor/ginkgo-perf_defconfig -cn Bluto
  - cd .. && rm -rf *
