--- 
kind: pipeline
name: dvstLab
steps: 
  - name: compile-test-lite
    image: "rzlamrr/dvstlab:lite"
    commands:
      - "rm -rf *"
      - "apt update -qq -y && DEBIAN_FRONTEND=noninteractive apt install -qq -y openjdk-8-jdk"
      - "git clone https://github.com/dvstLab/ginkgo-kernel -b berlian silont"
      - "cd silont"
      - "wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh"
      - "chmod +x compile.sh"
      - "bash compile.sh -clang proton -d vendor/ginkgo-perf_defconfig -cn Test"
      - "cd .. && rm -rf *"
    environment: 
      TOKED:
        from_secret: TOKED
      CHATID:
        from_secret: CHATID
      ORIGIN:
        from_secret: ORIGIN
      PATF:
        from_secret: PATF
      PAT:
        from_secret: PAT
