---
kind: pipeline
name: x10

steps:
- name: compile-x10
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless
  - git clone -qq --depth=1 $ORIGIN -b x10 silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c silont -ci drone -d silont-perf_defconfig -cn Arjasa
  - ls -a
  - ls out/
  - ls out/arch/arm64/boot

---
kind: pipeline
name: x11

steps:
- name: compile-x11
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless
  - git clone -qq --depth=1 $ORIGIN -b x11 silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c silont -ci drone -d silont-perf_defconfig -cn Bluto
  - ls -a
  - ls out/
  - ls out/arch/arm64/boot


---
kind: pipeline
name: n11

steps:
- name: compile-test
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless
  - ANDROID_BIN=${PREFIX:-${HOME}/usr}/bin
  - mkdir -p "${ANDROID_BIN}"
  - MKDTIMG_FOLDER=$(mktemp -d)
  - curl -LSs https://android.googlesource.com/platform/prebuilts/misc/+archive/master/linux-x86/libufdt.tar.gz | tar -C "${MKDTIMG_FOLDER}" -xzf -
  - cp "${MKDTIMG_FOLDER}"/mkdtimg "${ANDROID_BIN}"
  - rm -rf "${MKDTIMG_FOLDER}"
  - git clone -qq --depth=1 $ORIGIN -b n11 silont
  - cd silont
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh
  - chmod +x compile.sh
  - bash compile.sh -c silont -ci drone -d vendor/ginkgo-perf_defconfig -cn Test
  - ls -a
  - ls out/
  - ls out/arch/arm64/boot
